export const eslintStub = `/* eslint-disable */`;

export const autogeneratedHeaderStub = `
/*
-----------------------------------------------------
THIS FILE WAS AUTOMATICALLY GENERATED (DO NOT MODIFY)
-----------------------------------------------------
*/
`;
